### `Loading Library`

In [150]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import joblib 

from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import OneHotEncoder,StandardScaler,RobustScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier, StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

pd.set_option("display.max_columns", None) 
import warnings
warnings.filterwarnings("ignore")

In [27]:
df = pd.read_csv(r"D:\seccions route كلها\project_ML(تطبيق علي سشن 18)\Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [28]:
df = df.drop(columns=["customerID"])
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   str
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   str
 3   Dependents        7043 non-null   str
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   str
 6   MultipleLines     7043 non-null   str
 7   InternetService   7043 non-null   str
 8   OnlineSecurity    7043 non-null   str
 9   OnlineBackup      7043 non-null   str
 10  DeviceProtection  7043 non-null   str
 11  TechSupport       7043 non-null   str
 12  StreamingTV       7043 non-null   str
 13  StreamingMovies   7043 non-null   str
 14  Contract          7043 non-null   str
 15  PaperlessBilling  7043 non-null   str
 16  PaymentMethod     7043 non-null   str
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   str
 19  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(17)
memory usage: 1.7 MB

In [30]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [31]:
df.shape

(7043, 20)

In [32]:
df.columns.to_list()

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [33]:
df.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [34]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [35]:
df["TotalCharges"]=pd.to_numeric(df["TotalCharges"].astype(str).str.strip(),errors="coerce")
print(df["TotalCharges"].dtype)
df.isna().sum()

float64

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [36]:
numerical_columns = ['TotalCharges','MonthlyCharges','tenure','SeniorCitizen']
numerical_columns

['TotalCharges', 'MonthlyCharges', 'tenure', 'SeniorCitizen']

In [37]:
categorical_columns = ['gender'      ,         
'Partner'              ,
'Dependents'           ,
'PhoneService'      ,   
'MultipleLines'       ,
'InternetService'     ,
'OnlineSecurity'      ,
'OnlineBackup'        ,
'DeviceProtection'    ,
'TechSupport'         ,
'StreamingTV'         ,
'StreamingMovies'     ,
'Contract'            ,
'PaperlessBilling'    ,
'PaymentMethod'       ,]

categorical_columns

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

In [38]:
X=df.drop("Churn", axis=1)
y = df["Churn"]

In [39]:

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
    
)

In [40]:

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (5634, 19)
X_test shape: (1409, 19)
y_train shape: (5634,)
y_test shape: (1409,)

In [41]:
numerical_pipeline = Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler",  RobustScaler())
])
numerical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', RobustScaler())])

In [42]:
categorical_pipeline=Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ("encoder", OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
categorical_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [43]:
preprocessor = ColumnTransformer([
    ('numeric', numerical_pipeline,numerical_columns),
    ('categoric',categorical_pipeline,categorical_columns)
])
preprocessor

ColumnTransformer(transformers=[('numeric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', RobustScaler())]),
                                 ['TotalCharges', 'MonthlyCharges', 'tenure',
                                  'SeniorCitizen']),
                                ('categoric',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod'])])

In [44]:
X_train_prepar = preprocessor.fit_transform(X_train)

In [45]:
X_test_prepar =preprocessor.transform(X_test)

In [47]:
print('Train:', X_train_prepar.shape, '| Test:', X_test_prepar.shape)

Train: (5634, 45) | Test: (1409, 45)

### model----->`LogisticRegression`

In [49]:
model_logistic = LogisticRegression(max_iter=1000,random_state=42)

In [51]:
pipe_logistic = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_logistic)
])
pipe_logistic

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [52]:
pipe_logistic.fit(X_train,y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [55]:
y_pred = pipe_logistic.predict(X_test)
y_pred

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'],
      shape=(1409,), dtype=object)

In [64]:

print("Accuracy:", accuracy_score(y_test, y_pred))
#print("Precision:", precision_score(y_test, y_pred))
#print("Recall:", recall_score(y_test, y_pred))
#print("F1 Score:", f1_score(y_test, y_pred))

Accuracy: 0.8019872249822569

In [65]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

          No       0.89      0.85      0.87      1090
         Yes       0.55      0.65      0.60       319

    accuracy                           0.80      1409
   macro avg       0.72      0.75      0.73      1409
weighted avg       0.82      0.80      0.81      1409

In [66]:
print(confusion_matrix(y_pred,y_test))

[[923 167]
 [112 207]]

### model----->`svm`

In [67]:
model_svm = SVC(random_state=42)

In [68]:
pipe_svm = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_svm)
])
pipe_svm

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', SVC(random_state=42))])

In [69]:
pipe_svm.fit(X_train,y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', SVC(random_state=42))])

In [70]:
y_pred_svm = pipe_svm.predict(X_test)
y_pred_svm

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'],
      shape=(1409,), dtype=object)

In [71]:
print("Accuracy:", accuracy_score(y_test, y_pred_svm))

Accuracy: 0.7920511000709723

In [74]:
print(classification_report(y_pred_svm,y_test))

              precision    recall  f1-score   support

          No       0.90      0.83      0.86      1116
         Yes       0.50      0.64      0.56       293

    accuracy                           0.79      1409
   macro avg       0.70      0.74      0.71      1409
weighted avg       0.81      0.79      0.80      1409

In [73]:
print(confusion_matrix(y_pred_svm,y_test))

[[929 187]
 [106 187]]

### model----->`KNN`

In [76]:
model_KNN = KNeighborsClassifier()

In [77]:
pipe_KNN = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_KNN)
])
pipe_KNN

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', KNeighborsClassifier())])

In [78]:
pipe_KNN.fit(X_train,y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', KNeighborsClassifier())])

In [79]:
y_pred_KNN = pipe_KNN.predict(X_test)
y_pred_KNN

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'],
      shape=(1409,), dtype=object)

In [82]:
print("Accuracy:", accuracy_score(y_test, y_pred_KNN))

Accuracy: 0.7537260468417317

In [83]:
print(classification_report(y_pred_KNN,y_test))

              precision    recall  f1-score   support

          No       0.83      0.84      0.83      1022
         Yes       0.55      0.53      0.54       387

    accuracy                           0.75      1409
   macro avg       0.69      0.69      0.69      1409
weighted avg       0.75      0.75      0.75      1409

In [84]:
print(confusion_matrix(y_pred_KNN,y_test))

[[855 167]
 [180 207]]

### model----->`DesicionTree`

In [ ]:
model_desecion = DecisionTreeClassifier(random_state=42)

In [87]:
pipe_Desecion = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_desecion)
])
pipe_Desecion

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', DecisionTreeClassifier(random_state=42))])

In [88]:
pipe_Desecion.fit(X_train,y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', DecisionTreeClassifier(random_state=42))])

In [89]:
y_pred_Desecion = pipe_Desecion.predict(X_test)
y_pred_Desecion

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'],
      shape=(1409,), dtype=object)

In [90]:
print("Accuracy:", accuracy_score(y_test, y_pred_Desecion))

Accuracy: 0.7217885024840313

In [91]:
print(classification_report(y_pred_Desecion,y_test))

              precision    recall  f1-score   support

          No       0.81      0.81      0.81      1025
         Yes       0.49      0.48      0.48       384

    accuracy                           0.72      1409
   macro avg       0.65      0.65      0.65      1409
weighted avg       0.72      0.72      0.72      1409

In [92]:
print(confusion_matrix(y_pred_Desecion,y_test))

[[834 191]
 [201 183]]

### model----->` Random Forest`

In [103]:
model_Random = RandomForestClassifier()

In [104]:
pipe_Random = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_Random)
])
pipe_Random

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', RandomForestClassifier())])

In [105]:
pipe_Random.fit(X_train,y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', RandomForestClassifier())])

In [106]:
y_pred_Random = pipe_Random.predict(X_test)
y_pred_Random

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'],
      shape=(1409,), dtype=object)

In [107]:
print("Accuracy:", accuracy_score(y_test, y_pred_Random))

Accuracy: 0.7828246983676366

In [108]:
print(classification_report(y_pred_Random,y_test))

              precision    recall  f1-score   support

          No       0.88      0.83      0.86      1101
         Yes       0.50      0.61      0.55       308

    accuracy                           0.78      1409
   macro avg       0.69      0.72      0.70      1409
weighted avg       0.80      0.78      0.79      1409

In [109]:
print(confusion_matrix(y_pred_Random,y_test))

[[915 186]
 [120 188]]

### model----->`AdaBoost`

In [118]:
model_AdaBOOST = AdaBoostClassifier(random_state=42)

In [ ]:
pipe_Adeboost = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_AdaBOOST)
])
pipe_Adeboost

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', AdaBoostClassifier(random_state=42))])

In [113]:
pipe_Adeboost.fit(X_train,y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', AdaBoostClassifier(random_state=42))])

In [114]:
y_pred_Adeboost= pipe_Adeboost.predict(X_test)
y_pred_Adeboost

array(['No', 'Yes', 'No', ..., 'No', 'No', 'No'],
      shape=(1409,), dtype=object)

In [115]:
print("Accuracy:", accuracy_score(y_test,y_pred_Adeboost ))

Accuracy: 0.8019872249822569

In [119]:
print(classification_report(y_pred_Adeboost,y_test))

              precision    recall  f1-score   support

          No       0.89      0.84      0.87      1096
         Yes       0.55      0.65      0.59       313

    accuracy                           0.80      1409
   macro avg       0.72      0.75      0.73      1409
weighted avg       0.82      0.80      0.81      1409

In [120]:
print(confusion_matrix(y_pred_Adeboost,y_test))

[[926 170]
 [109 204]]

### model----->`XGBoost`

In [125]:
model_XGB =XGBClassifier(eval_metric="logloss",random_state=42)

In [126]:
pipe_XGB = Pipeline([
    ("preprosecc",preprocessor),
    ("model",model_XGB )
])
pipe_XGB

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [ ]:
#لزما تغير ال(Yes, No)لي ارقام علشان كده حولتها (Yes:1,no:0) (XGBoostمش بيبفهم النص)
Y_train = y_train.map({'No':0,'Yes':1})
Y_test = y_test.map({'No':0,'Yes':1})

In [130]:
pipe_XGB.fit(X_train,Y_train)

Pipeline(steps=[('preprosecc',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['TotalCharges',
                                                   'MonthlyCharges', 'tenure',
                                                   'SeniorCitizen']),
                                                 ('categoric',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [131]:
y_pred_XGB= pipe_XGB.predict(X_test)
y_pred_XGB

array([0, 1, 0, ..., 0, 0, 0], shape=(1409,))

In [135]:
print("Accuracy:", accuracy_score(Y_test, y_pred_XGB))

Accuracy: 0.7821149751596878

In [136]:
print(classification_report(y_pred_XGB,Y_test))

              precision    recall  f1-score   support

           0       0.87      0.84      0.85      1078
           1       0.53      0.60      0.56       331

    accuracy                           0.78      1409
   macro avg       0.70      0.72      0.71      1409
weighted avg       0.79      0.78      0.79      1409

In [137]:
print(confusion_matrix(Y_test, y_pred_XGB))

[[903 132]
 [175 199]]

In [142]:
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score
import pandas as pd

pipelines = {
    "Logistic Regression": pipe_logistic,
    "SVM": pipe_svm,
    "KNN": pipe_KNN,
    "Decision Tree": pipe_Desecion,
    "Random Forest": pipe_Random,
    "AdaBoost": pipe_Adeboost,
    "XGBoost": pipe_XGB
}

results = []
for name, pipe in pipelines.items():
    y_pred = pipe.predict(X_test)
    # ترجع ال0\1 زي مكانو (Yes,No)
    if name == "XGBoost":
        y_pred = np.where( y_pred_XGB == 1,"Yes","No")
    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred,pos_label="Yes"),
        "Recall": recall_score(y_test, y_pred,pos_label="Yes"),
        "F1": f1_score(y_test, y_pred,pos_label="Yes")
    })

results_df = pd.DataFrame(results).sort_values("F1", ascending=False)
results_df

                 Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.801987   0.648903  0.553476  0.597403
5             AdaBoost  0.801987   0.651757  0.545455  0.593886
6              XGBoost  0.782115   0.601208  0.532086  0.564539
1                  SVM  0.792051   0.638225  0.500000  0.560720
4        Random Forest  0.782825   0.610390  0.502674  0.551320
2                  KNN  0.753726   0.534884  0.553476  0.544021
3        Decision Tree  0.721789   0.476562  0.489305  0.482850

In [143]:
best_name = results_df.iloc[0]["Model"]
print(confusion_matrix(y_test, pipelines[best_name].predict(X_test)))

[[923 112]
 [167 207]]

### الـ Accuracy بتجاوب على سؤال واحد: 

كام توقع من كل 100 كان صح؟ مثلاً 0.80 يعني الموديل صح في 80% من العملاء.
المشكلة إن داتا الـ Churn imbalanced: أغلب العملاء بيفضلوا، وأقلية بس بتسيب. لو موديل قال "محدش هيسيب" للكل، هيجيب Accuracy حوالي 73-75% (نسبة العملاء اللي فضلوا)، وهو ما مسك ولا عميل واحد من اللي هيسيبوا.
وده بيظهر في جدولك: Logistic Regression وAdaBoost عندهم نفس الـ Accuracy (0.802)، بس الفرق بين 0.802 و0.75 (اللي ممكن يجيبه موديل "كسول") مش كبير زي ما الرقم بيوحي. عشان كده لازم نبص على باقي الـ metrics.

----------------------------------------------------------

### الـ Precision: لما الموديل يقول "هيسيب"، يبقى صح قد إيه؟

الـ Precision = من كل العملاء اللي الموديل قال عنهم "هيسيبوا"، كام فعلاً سابوا.
Logistic Regression عنده 0.649، يعني من كل 100 عميل بيحذر منهم، حوالي 65 فعلاً هيسيبوا و35 إنذار كاذب. الـ Precision مهمة لو تكلفة التواصل مع العميل عالية (خصم، مكالمة، عرض)، لأنك مش عايز تصرف على ناس مش هيمشوا.

----------------------------------------------------------------------------------------

### الـ Recall: من العملاء اللي فعلاً هيسيبوا، مسكنا كام؟
الـ Recall = من كل العملاء اللي فعلاً سابوا، كام الموديل اكتشفهم.
Logistic Regression عنده 0.553، يعني بيمسك حوالي 55% بس من اللي هيسيبوا، والـ 45% الباقيين بيعدوا من غير ما حد ياخد باله. دي الـ False Negatives، وفي مشكلة الـ Churn هي الأغلى: خسارة عميل أكتر تكلفة من عرض لعميل كان هيفضل أصلاً.

ولاحظ KNN: الـ Recall بتاعه (0.553) نفس Logistic Regression، بس الـ Precision بتاعه ضعيف (0.535)، يعني بيمسك نفس العدد بس بإنذارات كاذبة أكتر.

--------------------------------------------------------------------------------------------------------
### الـ F1: الموازنة بين الاتنين
فيه تعارض بين Precision وRecall: لو خليت الموديل يحذر من أي حد، الـ Recall يزيد والـ Precision تقع، والعكس. الـ F1 هو المتوسط التوافقي بينهم، فبيكافئ الموديل المتوازن ويعاقب اللي بيضحي بواحد عشان التاني.
عشان كده رتبنا الجدول بالـ F1، وLogistic Regression جه الأول (0.597) لأنه الأوازن.

---------------------------------------------------------------------

### `الخلاصة`
الـ Accuracy بتخدع في الداتا imbalanced، وفرقها بين الموديلز الأول صغير.
الـ Recall هو الأهم للـ business هنا، لأننا عايزين نمسك أكبر عدد من العملاء قبل ما يسيبوا.
الـ F1 معيار الترتيب العادل لأنه بيجمع Precision وRecall.
Logistic Regression هو الأفضل كـ baseline (F1 = 0.597)، وAdaBoost قريب جداً منه.

### `Gridsearch with logistic`

In [145]:
param_grid = {
    'model__C': [0.01, 0.1, 1, 10, 100],
    'model__class_weight': [None, "balanced"]
}

In [146]:
grid_search = GridSearchCV(
    estimator=pipe_logistic,
    param_grid=param_grid,
    cv=5, 
    scoring='accuracy',
    n_jobs=-1
)
grid_search.fit(X_train,y_train)
print(grid_search.best_params_)
print(grid_search.best_score_)

{'model__C': 100, 'model__class_weight': None}
0.8045766673338577

In [147]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
import numpy as np

scores = cross_val_score(pipe_logistic, X_train, y_train,
                         cv=StratifiedKFold(5, shuffle=True, random_state=42),
                         scoring="accuracy")
print(scores, scores.mean())

[0.79680568 0.78083407 0.80124224 0.81721384 0.81172291] 0.801563748520491

### `save model`

In [151]:
best_logistic = grid_search.best_estimator_
joblib.dump(best_logistic, 'Best_Model.pkl')

['Best_Model.pkl']

In [152]:
loaded_classifier = joblib.load('Best_Model.pkl')